name: boca-playwright
services:
    script:
        build: .
        stdin_open: true
        tty: true
        volumes:
            - ./resources/mocks:/mocks
        network_mode: host
        command: /mocks/create_user.json shouldCreateUser
