name: boca-playwright
services:
    script:
        build: .
        stdin_open: true
        tty: true
        volumes:
            - ./resources:/resources
        network_mode: host
        command: /resources/mocks/delete_user.json shouldDeleteUser
