import {
  shouldActivateContest,
  shouldCreateContest,
  shouldGetContest,
  shouldGetContests,
  shouldUpdateContest,
  shouldCreateAnswer,
  shouldDeleteAnswer,
  shouldDeleteAnswers,
  shouldGetAnswer,
  shouldGetAnswers,
  shouldUpdateAnswer,
  shouldCreateLanguage,
  shouldDeleteLanguage,
  shouldDeleteLanguages,
  shouldGetLanguage,
  shouldGetLanguages,
  shouldUpdateLanguage,
  shouldCreateProblem,
  shouldDeleteProblem,
  shouldDeleteProblems,
  shouldDownloadProblem,
  shouldRestoreProblem,
  shouldRestoreProblems,
  shouldGetProblem,
  shouldGetProblems,
  shouldUpdateProblem,
  shouldCreateSite,
  shouldDisableLoginSite,
  shouldEnableLoginSite,
  shouldGetSite,
  shouldGetSites,
  shouldForceLogoffSite,
  shouldUpdateSite,
  shouldCreateUser,
  shouldDeleteUser,
  shouldDeleteUsers,
  shouldRestoreUser,
  shouldRestoreUsers,
  shouldGetUser,
  shouldGetUsers,
  shouldImportUsers,
  shouldUpdateUser,
  shouldDownloadRuns,
  shouldDownloadRun,
  shouldGetRun,
  shouldGetRuns,
  shouldSubmitRun
} from '..';
import { Setup } from '../data/setup';

export const methods: Record<string, (setup: Setup) => Promise<void>> = {
  // Contests
  activateContest: shouldActivateContest,
  createContest: shouldCreateContest,
  getContest: shouldGetContest,
  getContests: shouldGetContests,
  updateContest: shouldUpdateContest,
  // Answers
  createAnswer: shouldCreateAnswer,
  deleteAnswer: shouldDeleteAnswer,
  deleteAnswers: shouldDeleteAnswers,
  getAnswer: shouldGetAnswer,
  getAnswers: shouldGetAnswers,
  updateAnswer: shouldUpdateAnswer,
  // Languages
  createLanguage: shouldCreateLanguage,
  deleteLanguage: shouldDeleteLanguage,
  deleteLanguages: shouldDeleteLanguages,
  getLanguage: shouldGetLanguage,
  getLanguages: shouldGetLanguages,
  updateLanguage: shouldUpdateLanguage,
  // Problems
  createProblem: shouldCreateProblem,
  deleteProblem: shouldDeleteProblem,
  deleteProblems: shouldDeleteProblems,
  disableProblem: shouldDeleteProblem,
  disableProblems: shouldDeleteProblems,
  downloadProblem: shouldDownloadProblem,
  enableProblem: shouldRestoreProblem,
  enableProblems: shouldRestoreProblems,
  getProblem: shouldGetProblem,
  getProblems: shouldGetProblems,
  restoreProblem: shouldRestoreProblem,
  restoreProblems: shouldRestoreProblems,
  updateProblem: shouldUpdateProblem,
  // Sites
  createSite: shouldCreateSite,
  disableLoginSite: shouldDisableLoginSite,
  enableLoginSite: shouldEnableLoginSite,
  getSite: shouldGetSite,
  getSites: shouldGetSites,
  forceLogoffSite: shouldForceLogoffSite,
  updateSite: shouldUpdateSite,
  // Users
  createUser: shouldCreateUser,
  deleteUser: shouldDeleteUser,
  deleteUsers: shouldDeleteUsers,
  disableUser: shouldDeleteUser,
  disableUsers: shouldDeleteUsers,
  enableUser: shouldRestoreUser,
  enableUsers: shouldRestoreUsers,
  getUser: shouldGetUser,
  getUsers: shouldGetUsers,
  importUsers: shouldImportUsers,
  restoreUser: shouldRestoreUser,
  restoreUsers: shouldRestoreUsers,
  updateUser: shouldUpdateUser,
  // Reports
  downloadRuns: shouldDownloadRuns,
  downloadRun: shouldDownloadRun,
  getRun: shouldGetRun,
  getRuns: shouldGetRuns,
  submitRun: shouldSubmitRun
};
